PLUGIN_NAME=		kontrol-proxy-sso
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Kerberos and NTLM authentication
PLUGIN_DEPENDS=		msktutil cyrus-sasl-gssapi samba416
PLUGIN_MAINTAINER=	contato@kontrol.com.br
PLUGIN_WWW=		https://kontrol.com.br

.include "../../Mk/plugins.mk"
